import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { DashboardSidebar } from "@/components/sidebar/DashboardSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import TranslationsProvider from "@/i18n/TranslationsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranslationsProvider locale={locale} namespaces={["common"]}>
          <SidebarProvider>
            <div className="flex">
              <DashboardSidebar />
              <main className="w-full">{children}</main>
            </div>
          </SidebarProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
